apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
      - name: my-api
        image: flask-k8s-app:latest  
        imagePullPolicy: Never   
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: my-api-service
spec:
  type: NodePort
  selector:
    app: my-api
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
